Add rustfmt check to pre-commit

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -1,8 +1,13 @@
 #!/usr/bin/env bash
 
-if cargo run --bin kra-lint-test --quiet ; then
-    exit 0
-else
+if ! cargo fmt --check ; then
+    echo "pre-commit: rustfmt failure, commit aborted"
+    exit 1
+fi
+
+if ! cargo run --bin kra-lint-test --quiet ; then
     echo "pre-commit: test failure, commit aborted"
     exit 1
 fi
+
+exit 0
